[package]
name = "dispatch"
version = "0.1.0"
edition = "2021"


[dependencies]
ckb-std = { version = "0.13.0" }
hex = { version = "0.4.3", default-features = false, features = ["alloc"]}
blake2b-rs = {version = "0.2.0", default-features = false}
strum = { default-features = false, features = ["derive"], version = "0.25" }
strum_macros = "0.25"
num_enum = { version = "0.6.1", default-features = false }
das-types = { git = "https://github.com/dotbitHQ/das-contracts-private.git", default-features = false, rev = "5f7e29f" }
das-core = { git = "https://github.com/dotbitHQ/das-contracts-private.git", default-features = false, rev = "5f7e29f" }
das-dynamic-libs = { git = "https://github.com/dotbitHQ/das-contracts-private.git",  default-features = false, rev = "5f7e29f" }
das-proc-macro = { path = "../libs/das-proc-macro" }
#serde = { version = "1.0", default-features = false, features = ["alloc"] }
#serde-json-core = "0.5"
#sha2 = {version = "0.10", default-features = false}
#base64-url = {version = "2.0", default-features = false}
#base64 = {version = "0.21", default-features = false, features = ["alloc"]}
ethnum = "1.4"

[features]
default = []
mainnet = ["das-core/mainnet", "das-types/no_std", "das-dynamic-libs/mainnet"]
testnet2 = ["das-core/testnet", "das-types/no_std", "das-dynamic-libs/testnet"]
testnet3 = ["das-core/testnet", "das-types/no_std", "das-dynamic-libs/testnet"]

#for test
test-single = ["das-proc-macro/test-single"]
test-partial = ["das-proc-macro/test-partial"]
test-dev = ["das-proc-macro/test-dev"]
test-all = ["das-proc-macro/test-all"]
#[package.metadata.bootimage]
#test-success-exit-code = -1


[profile.dev]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
